magick.exe .\r01.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_assist.bmp
magick.exe .\r04.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_headshot.bmp
magick.exe .\r05.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_avenger.bmp
magick.exe .\r06.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_savior.bmp
magick.exe .\r09.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_mvp.bmp
magick.exe .\r10.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_handgun.bmp
magick.exe .\r11.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_assault.bmp
magick.exe .\r12.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_carbin.bmp
magick.exe .\r13.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_sniper.bmp
magick.exe .\r14.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_lmg.bmp
magick.exe .\r15.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_dmr.bmp
magick.exe .\r16.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_pdw.bmp
magick.exe .\r17.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_shotgun.bmp
magick.exe .\r18.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_melee.bmp
magick.exe .\r39.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:rbn_marksman.bmp

magick.exe .\m01.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_assist.bmp
magick.exe .\m04.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_headshot.bmp
magick.exe .\m05.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_avenger..bmp
magick.exe .\m06.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_savior.bmp
magick.exe .\m09.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_mvp.bmp
magick.exe .\m10.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_handgun.bmp
magick.exe .\m11.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_assault.bmp
magick.exe .\m12.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_carbin.bmp
magick.exe .\m13.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_sniper.bmp
magick.exe .\m14.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_lmg.bmp
magick.exe .\m15.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_dmr.bmp
magick.exe .\m16.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_pdw.bmp
magick.exe .\m17.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_shotgun.bmp
magick.exe .\m18.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_melee.bmp
magick.exe .\m39.dds -compress None -colors 256 -channel alpha -threshold 15 +channel -background #ff00ff -alpha background -alpha off -gravity North -extent 512x512 bmp3:mdl_marksman.bmp
